
COLUMSPAN: int = 5
SORTING_SPEED: int = 75 #lower value = faster sorting
RANDOM_SEED_START: int = 5
RANDOM_SEED_END: int = 100
ARRAYSIZE: int = 125

CANVAS_WIDTH:int = 1920
CANVAS_HEIGHT:int = 1080
BAR_HEIGHT:int = CANVAS_HEIGHT - 1

RECTANGLE_COLOR: str = "#40E0D0"
RECTANGLE_OBJECT_TAG: str = "rect"
CANVAS_BACKGROUND_COLOR: str = "white"
ROOT_TITLE: str = "Search Algorithm Presentation"
GEOMETRY_MEASUREMENT: str = "1920x1200"